#!/bin/bash
#
# Randomly display a wallpaper every 5 minutes.

while true;
do
   find /home/souly/Wallpapers -type f -name '*.jpg' -o -name '*.png' | shuf -n 1 | xargs feh --bg-scale
   sleep 5m
done &
